#!/usr/bin/env node

/**
 * PostCSS plugin to remove invalid CSS selectors with malformed pseudo-classes
 * This helps clean up CSS generated by Tailwind that contains invalid selectors
 */

const fs = require('fs');
const path = require('path');

function removeInvalidSelectors(filePath) {
  try {
    let content = fs.readFileSync(filePath, 'utf-8');
    
    // Pattern to match invalid pseudo-class selectors like :hoversvg
    const invalidSelectorPattern = /\.hover\\:text-slate-300:hoversvg\s*\{[^}]+\}/g;
    const altPattern = /\.hover\\:.*:hoversvg\s*\{[^}]*\}/g;
    
    let removed = false;
    if (invalidSelectorPattern.test(content)) {
      content = content.replace(invalidSelectorPattern, '');
      removed = true;
    }
    if (altPattern.test(content)) {
      content = content.replace(altPattern, '');
      removed = true;
    }
    
    if (removed) {
      fs.writeFileSync(filePath, content, 'utf-8');
      console.log(`✓ Removed invalid CSS selectors from ${filePath}`);
      return true;
    }
  } catch (error) {
    console.error(`Error processing ${filePath}:`, error.message);
  }
  return false;
}

// Clean the generated globals.css file after build
const globalsPath = path.join(__dirname, '..', 'src/app/globals.css');
if (fs.existsSync(globalsPath)) {
  removeInvalidSelectors(globalsPath);
}

// Clean all CSS files in .next directory if it exists
const nextDir = path.join(__dirname, '..', '.next');
if (fs.existsSync(nextDir)) {
  try {
    const walkDir = (dir) => {
      const files = fs.readdirSync(dir);
      files.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);
        if (stat.isDirectory()) {
          walkDir(filePath);
        } else if (file.endsWith('.css')) {
          removeInvalidSelectors(filePath);
        }
      });
    };
    walkDir(nextDir);
  } catch (error) {
    // Ignore errors when walking .next directory
  }
}
