/**
 * Demo Mode — Mock Data
 * All demo data lives here. The demo API route (/api/tenants/demo/[...path]) serves this data.
 * Write operations (POST/PUT/DELETE) echo back the submitted payload — changes are NOT persisted.
 */

export const DEMO_TENANT_ID = "demo";

// ─── Tenant ──────────────────────────────────────────────────────────────────
export const DEMO_TENANT = {
  id: "demo",
  name: "Tienda Demo",
  slug: "demo",
  plan: "enterprise",
  features: {
    pos: true,
    inventory: true,
    employees: true,
    schedules: true,
    payroll: true,
    reports: true,
    customRoles: true,
    api: true,
    loyalty: true,
  },
  paid_until: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
  created_at: "2024-01-01T00:00:00Z",
  updated_at: new Date().toISOString(),
};

// ─── Settings ─────────────────────────────────────────────────────────────────
export const DEMO_SETTINGS = {
  companyName: "Tienda Demo S.A.",
  companyPhone: "+505 2222-3333",
  companyEmail: "demo@tiendademo.com",
  companyWebsite: "www.tiendademo.com",
  companyRuc: "J0310000123456",
  currency: "NIO",
  timezone: "America/Managua",
  language: "es",
  usdExchangeRate: 36.80,
  logoUrl: null,
  posConfig: { roundTotal: false, printReceipt: true },
  payrollConfig: { frequency: "monthly", weekStartDay: 1, monthStartDay: 1 },
};

// ─── Categories ───────────────────────────────────────────────────────────────
export const DEMO_CATEGORIES = [
  { id: "cat-1", tenant_id: "demo", name: "Bebidas", description: "Refrescos, jugos, agua", sort_order: 1, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-2", tenant_id: "demo", name: "Alimentos", description: "Snacks, galletas, comida rápida", sort_order: 2, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-3", tenant_id: "demo", name: "Electrónica", description: "Accesorios y gadgets", sort_order: 3, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-4", tenant_id: "demo", name: "Higiene Personal", description: "Jabones, shampoo, desodorante", sort_order: 4, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const DEMO_PRODUCTS = [
  {
    id: "prod-1",
    tenant_id: "demo",
    name: "Coca-Cola",
    sku: "BEB-001",
    price: 35,
    quantity: 48,
    stock_quantity: 48,
    category_id: "cat-1",
    description: "Refresco 355ml",
    min_stock: 10,
    sort_order: 1,
    has_variants: false,
    variants: [],
    cost_price: 20,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-2",
    tenant_id: "demo",
    name: "Pepsi",
    sku: "BEB-002",
    price: 30,
    quantity: 36,
    stock_quantity: 36,
    category_id: "cat-1",
    description: "Refresco 355ml",
    min_stock: 10,
    sort_order: 2,
    has_variants: false,
    variants: [],
    cost_price: 17,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-3",
    tenant_id: "demo",
    name: "Agua Purificada",
    sku: "BEB-003",
    price: 15,
    quantity: 120,
    stock_quantity: 120,
    category_id: "cat-1",
    description: "Botella 500ml",
    min_stock: 20,
    sort_order: 3,
    has_variants: false,
    variants: [],
    cost_price: 7,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-4",
    tenant_id: "demo",
    name: "Café Presto",
    sku: "BEB-004",
    price: 50,
    quantity: 3,
    stock_quantity: 3,
    category_id: "cat-1",
    description: "Café instantáneo 150g (stock bajo)",
    min_stock: 5,
    sort_order: 4,
    has_variants: false,
    variants: [],
    cost_price: 28,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-5",
    tenant_id: "demo",
    name: "Chips Sabritas",
    sku: "ALI-001",
    price: 25,
    quantity: 60,
    stock_quantity: 60,
    category_id: "cat-2",
    description: "Papas fritas 150g",
    min_stock: 10,
    sort_order: 5,
    has_variants: false,
    variants: [],
    cost_price: 14,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-6",
    tenant_id: "demo",
    name: "Galletas Oreo",
    sku: "ALI-002",
    price: 45,
    quantity: 40,
    stock_quantity: 40,
    category_id: "cat-2",
    description: "Galletas de chocolate 154g",
    min_stock: 8,
    sort_order: 6,
    has_variants: false,
    variants: [],
    cost_price: 25,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-7",
    tenant_id: "demo",
    name: "Cable USB-C",
    sku: "ELE-001",
    price: 180,
    quantity: 15,
    stock_quantity: 15,
    category_id: "cat-3",
    description: "Cable de carga USB-C 1m",
    min_stock: 3,
    sort_order: 7,
    has_variants: true,
    cost_price: 90,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    variants: [
      { id: "var-7-1", product_id: "prod-7", tenant_id: "demo", label: "1 metro", sku: "ELE-001-1M", price: 180, stock_quantity: 10, sort_order: 1, cost_price: 90 },
      { id: "var-7-2", product_id: "prod-7", tenant_id: "demo", label: "2 metros", sku: "ELE-001-2M", price: 250, stock_quantity: 5, sort_order: 2, cost_price: 130 },
    ],
  },
  {
    id: "prod-8",
    tenant_id: "demo",
    name: "Jabón Dove",
    sku: "HIG-001",
    price: 55,
    quantity: 25,
    stock_quantity: 25,
    category_id: "cat-4",
    description: "Jabón en barra 135g",
    min_stock: 5,
    sort_order: 8,
    has_variants: false,
    variants: [],
    cost_price: 30,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-9",
    tenant_id: "demo",
    name: "Shampoo Head & Shoulders",
    sku: "HIG-002",
    price: 220,
    quantity: 0,
    stock_quantity: 0,
    category_id: "cat-4",
    description: "Shampoo anticaspa 400ml (agotado)",
    min_stock: 3,
    sort_order: 9,
    has_variants: false,
    variants: [],
    cost_price: 130,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Taxes ────────────────────────────────────────────────────────────────────
export const DEMO_TAXES = [
  {
    id: "tax-1",
    tenant_id: "demo",
    name: "IVA",
    rate: 15,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
const now = new Date();
const d = (offsetDays: number, h = 10, m = 0) => {
  const d = new Date(now);
  d.setDate(d.getDate() - offsetDays);
  d.setHours(h, m, 0, 0);
  return d.toISOString();
};

export const DEMO_TRANSACTIONS = [
  {
    id: "TXN-DEMO-001",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-1", name: "Coca-Cola", quantity: 2, price: 35, cost_price: 20, total: 70 },
      { productId: "prod-5", name: "Chips Sabritas", quantity: 1, price: 25, cost_price: 14, total: 25 },
    ],
    subtotal: 95,
    discount: 0,
    tax: 14.25,
    total: 109.25,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(0, 9, 15),
    updated_at: d(0, 9, 15),
  },
  {
    id: "TXN-DEMO-002",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "María Demo",
    items: [
      { productId: "prod-7", variantId: "var-7-1", name: "Cable USB-C — 1 metro", quantity: 1, price: 180, cost_price: 90, total: 180 },
      { productId: "prod-8", name: "Jabón Dove", quantity: 3, price: 55, cost_price: 30, total: 165 },
    ],
    subtotal: 345,
    discount: 20,
    tax: 48.75,
    total: 373.75,
    payment_method: "CARD",
    status: "COMPLETED",
    created_at: d(0, 11, 30),
    updated_at: d(0, 11, 30),
  },
  {
    id: "TXN-DEMO-003",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-3", name: "Agua Purificada", quantity: 6, price: 15, cost_price: 7, total: 90 },
      { productId: "prod-6", name: "Galletas Oreo", quantity: 2, price: 45, cost_price: 25, total: 90 },
    ],
    subtotal: 180,
    discount: 0,
    tax: 27,
    total: 207,
    payment_method: "TRANSFER",
    status: "COMPLETED",
    created_at: d(1, 14, 45),
    updated_at: d(1, 14, 45),
  },
  {
    id: "TXN-DEMO-004",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "María Demo",
    items: [
      { productId: "prod-2", name: "Pepsi", quantity: 4, price: 30, cost_price: 17, total: 120 },
    ],
    subtotal: 120,
    discount: 0,
    tax: 18,
    total: 138,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(2, 10, 0),
    updated_at: d(2, 10, 0),
  },
  {
    id: "TXN-DEMO-005",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-4", name: "Café Presto", quantity: 1, price: 50, cost_price: 28, total: 50 },
      { productId: "prod-7", variantId: "var-7-2", name: "Cable USB-C — 2 metros", quantity: 1, price: 250, cost_price: 130, total: 250 },
    ],
    subtotal: 300,
    discount: 30,
    tax: 40.5,
    total: 310.5,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(3, 16, 20),
    updated_at: d(3, 16, 20),
  },
];

// ─── Employees ────────────────────────────────────────────────────────────────
export const DEMO_EMPLOYEES = [
  {
    id: "emp-1",
    tenant_id: "demo",
    first_name: "Juan",
    last_name: "García",
    email: "juan.garcia@demo.com",
    phone: "+505 8888-1111",
    role_id: "cashier",
    salary: 8500,
    status: "ACTIVE",
    hire_date: "2023-03-15",
    created_at: "2023-03-15T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-2",
    tenant_id: "demo",
    first_name: "María",
    last_name: "López",
    email: "maria.lopez@demo.com",
    phone: "+505 8888-2222",
    role_id: "cashier",
    salary: 8500,
    status: "ACTIVE",
    hire_date: "2023-06-01",
    created_at: "2023-06-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-3",
    tenant_id: "demo",
    first_name: "Carlos",
    last_name: "Martínez",
    email: "carlos.martinez@demo.com",
    phone: "+505 8888-3333",
    role_id: "manager",
    salary: 14000,
    status: "ACTIVE",
    hire_date: "2022-11-01",
    created_at: "2022-11-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-4",
    tenant_id: "demo",
    first_name: "Ana",
    last_name: "Rodríguez",
    email: "ana.rodriguez@demo.com",
    phone: "+505 8888-4444",
    role_id: "employee",
    salary: 7000,
    status: "INACTIVE",
    hire_date: "2023-01-10",
    created_at: "2023-01-10T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Attendance (Time Entries) ─────────────────────────────────────────────────
export const DEMO_ATTENDANCE = [
  {
    id: "att-1",
    tenant_id: "demo",
    employee_id: "emp-1",
    employee_first_name: "Juan",
    employee_last_name: "García",
    check_in: d(0, 8, 0),
    check_out: d(0, 17, 0),
    date: now.toISOString().split("T")[0],
    notes: "",
    created_at: d(0, 8, 0),
  },
  {
    id: "att-2",
    tenant_id: "demo",
    employee_id: "emp-2",
    employee_first_name: "María",
    employee_last_name: "López",
    check_in: d(0, 8, 30),
    check_out: d(0, 17, 30),
    date: now.toISOString().split("T")[0],
    notes: "",
    created_at: d(0, 8, 30),
  },
  {
    id: "att-3",
    tenant_id: "demo",
    employee_id: "emp-1",
    employee_first_name: "Juan",
    employee_last_name: "García",
    check_in: d(1, 8, 0),
    check_out: d(1, 17, 0),
    date: new Date(now.getTime() - 86400000).toISOString().split("T")[0],
    notes: "Turno normal",
    created_at: d(1, 8, 0),
  },
  {
    id: "att-4",
    tenant_id: "demo",
    employee_id: "emp-3",
    employee_first_name: "Carlos",
    employee_last_name: "Martínez",
    check_in: d(1, 7, 0),
    check_out: d(1, 16, 0),
    date: new Date(now.getTime() - 86400000).toISOString().split("T")[0],
    notes: "Turno mañana",
    created_at: d(1, 7, 0),
  },
];

// ─── Payroll ──────────────────────────────────────────────────────────────────
export const DEMO_PAYROLL_CONFIG = {
  frequency: "monthly",
  weekStartDay: 1,
  monthStartDay: 1,
};

export const DEMO_SALARY_PAYMENTS = [
  // ── Avril 2026 ────────────────────────────────────────────────────────────
  {
    id: "pay-1",
    tenant_id: "demo",
    employee_id: "emp-1",
    employees: { first_name: "Juan", last_name: "García" },
    period_start: "2026-04-01",
    period_end: "2026-04-30",
    hours_worked: 176,
    hourly_rate: 53.125,
    amount: 9350,
    notes: "Pago abril con horas extras",
    paid_at: "2026-04-30",
    created_at: "2026-04-30T00:00:00Z",
  },
  {
    id: "pay-2",
    tenant_id: "demo",
    employee_id: "emp-2",
    employees: { first_name: "María", last_name: "López" },
    period_start: "2026-04-01",
    period_end: "2026-04-30",
    hours_worked: 160,
    hourly_rate: 53.125,
    amount: 8500,
    notes: "",
    paid_at: "2026-04-30",
    created_at: "2026-04-30T00:00:00Z",
  },
  {
    id: "pay-3",
    tenant_id: "demo",
    employee_id: "emp-3",
    employees: { first_name: "Carlos", last_name: "Martínez" },
    period_start: "2026-04-01",
    period_end: "2026-04-30",
    hours_worked: 160,
    hourly_rate: 87.5,
    amount: 14000,
    notes: "",
    paid_at: "2026-04-30",
    created_at: "2026-04-30T00:00:00Z",
  },
  // ── Mai 2026 (mois en cours) ──────────────────────────────────────────────
  {
    id: "pay-4",
    tenant_id: "demo",
    employee_id: "emp-1",
    employees: { first_name: "Juan", last_name: "García" },
    period_start: "2026-05-01",
    period_end: "2026-05-31",
    hours_worked: 176,
    hourly_rate: 53.125,
    amount: 9350,
    notes: "Pago mayo con horas extras",
    paid_at: "2026-05-01",
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "pay-5",
    tenant_id: "demo",
    employee_id: "emp-2",
    employees: { first_name: "María", last_name: "López" },
    period_start: "2026-05-01",
    period_end: "2026-05-31",
    hours_worked: 160,
    hourly_rate: 53.125,
    amount: 8500,
    notes: "",
    paid_at: "2026-05-01",
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "pay-6",
    tenant_id: "demo",
    employee_id: "emp-3",
    employees: { first_name: "Carlos", last_name: "Martínez" },
    period_start: "2026-05-01",
    period_end: "2026-05-31",
    hours_worked: 160,
    hourly_rate: 87.5,
    amount: 14000,
    notes: "",
    paid_at: "2026-05-01",
    created_at: "2026-05-01T00:00:00Z",
  },
];

// ─── Roles ────────────────────────────────────────────────────────────────────
export const DEMO_ROLES = [
  {
    id: "admin",
    tenant_id: "demo",
    slug: "admin",
    name: "Administrador",
    description: "Acceso completo al sistema",
    permissions: [
      "pos.view", "pos.create", "pos.void", "pos.configure",
      "inventory.view", "inventory.create", "inventory.edit", "inventory.delete", "inventory.adjust",
      "employees.view", "employees.create", "employees.edit", "employees.delete",
      "schedules.view", "schedules.edit", "schedules.checkin",
      "payroll.view", "payroll.create", "payroll.approve", "payroll.pay",
      "settings.view", "settings.edit", "settings.manage_roles",
      "reports.view", "reports.export",
    ],
    is_system: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "manager",
    tenant_id: "demo",
    slug: "manager",
    name: "Gerente",
    description: "Gestión de empleados, inventario y reportes",
    permissions: [
      "pos.view", "pos.create",
      "inventory.view", "inventory.create", "inventory.edit",
      "employees.view", "employees.create", "employees.edit",
      "schedules.view", "schedules.edit",
      "payroll.view", "payroll.create",
      "reports.view", "reports.export",
    ],
    is_system: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cashier",
    tenant_id: "demo",
    slug: "cashier",
    name: "Cajero",
    description: "Operaciones de caja",
    permissions: ["pos.view", "pos.create", "schedules.checkin"],
    is_system: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Loyalty ──────────────────────────────────────────────────────────────────
export const DEMO_LOYALTY_SETTINGS = {
  loyalty_module_enabled: true,
  points_per_purchase: 1,
  min_purchase_for_points: 100,
};

export const DEMO_LOYAL_CUSTOMERS = [
  {
    id: "lc-1",
    tenant_id: "demo",
    card_number: "12345",
    name: "Roberto Sánchez",
    phone: "+505 7777-1111",
    email: "roberto@demo.com",
    total_accumulated: 3500,
    total_visits: 28,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "lc-2",
    tenant_id: "demo",
    card_number: "67890",
    name: "Lucía Peña",
    phone: "+505 7777-2222",
    email: "lucia@demo.com",
    total_accumulated: 1200,
    total_visits: 10,
    created_at: "2024-02-01T00:00:00Z",
  },
];

// ─── Payment status ───────────────────────────────────────────────────────────
export const DEMO_PAYMENT_STATUS = {
  is_paid: true,
  paid_until: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
  plan: "enterprise",
  amount: 0,
};

// ─── Contacts ─────────────────────────────────────────────────────────────────
export const DEMO_CONTACTS_INITIAL = [
  {
    id: "demo-contact-1",
    tenant_id: "demo",
    full_name: "María García",
    email: "maria.garcia@ejemplo.com",
    phone_number: "+505 8765-4321",
    whatsapp_number: "+505 8765-4321",
    company_name: "Distribuidora García",
    address: "Barrio Los Robles, Casa 12",
    city: "Managua",
    country: "Nicaragua",
    postal_code: "",
    position: "Gerente General",
    notes: "Cliente frecuente, prefiere pago en efectivo.",
    google_maps_link: "",
    photo_url: null,
    created_at: "2024-03-15T10:00:00Z",
    updated_at: "2024-03-15T10:00:00Z",
  },
  {
    id: "demo-contact-2",
    tenant_id: "demo",
    full_name: "Carlos Rodríguez",
    email: "c.rodriguez@suplidores.ni",
    phone_number: "+505 2222-3344",
    whatsapp_number: "",
    company_name: "Suplidores del Norte",
    address: "Km 5 Carretera Norte",
    city: "Managua",
    country: "Nicaragua",
    postal_code: "",
    position: "Representante de Ventas",
    notes: "Proveedor principal de electrónicos.",
    google_maps_link: "",
    photo_url: null,
    created_at: "2024-04-01T09:30:00Z",
    updated_at: "2024-04-01T09:30:00Z",
  },
];

// ─── Suppliers ────────────────────────────────────────────────────────────────
export const DEMO_SUPPLIERS_INITIAL = [
  {
    id: "sup-1",
    tenant_id: "demo",
    name: "Distribuidora Nacional",
    description: "Proveedor de bebidas y alimentos",
    contact: "+505 2200-1000",
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "sup-2",
    tenant_id: "demo",
    name: "TecnoElect SA",
    description: "Accesorios electrónicos y cables",
    contact: "+505 2200-2000",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "sup-3",
    tenant_id: "demo",
    name: "Higiene y Más",
    description: "Productos de higiene y limpieza",
    contact: "+505 2200-3000",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
];

// ─── Expense categories ───────────────────────────────────────────────────────
export const DEMO_EXPENSE_CATEGORIES = [
  { id: "ecat-1", tenant_id: "demo", name: "Instalaciones", description: "Alquiler y mantenimiento del local", created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-2", tenant_id: "demo", name: "Servicios",     description: "Electricidad, agua, internet",          created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-3", tenant_id: "demo", name: "Inventario",    description: "Reposición de mercancía",               created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-4", tenant_id: "demo", name: "Suministros",   description: "Material de oficina y limpieza",        created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-5", tenant_id: "demo", name: "Transporte",    description: "Fletes y gasolina",                     created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];

// ─── Fixed expenses ───────────────────────────────────────────────────────────
export const DEMO_FIXED_EXPENSES = [
  {
    id: "fix-1",
    tenant_id: "demo",
    name: "Alquiler del local",
    amount: 5000,
    category: "Instalaciones",
    supplier_id: null,
    day_of_month: 1,
    notes: "Pago mensual por adelantado",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "fix-2",
    tenant_id: "demo",
    name: "Servicio de Internet",
    amount: 1500,
    category: "Servicios",
    supplier_id: null,
    day_of_month: 5,
    notes: "Fibra óptica 100 Mbps",
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Expenses ─────────────────────────────────────────────────────────────────
// Dates in current month (May 2026) so they appear in the Bilan's default filter
export const DEMO_EXPENSES_INITIAL = [
  {
    id: "exp-1",
    tenant_id: "demo",
    supplier_id: null,
    amount: 5000,
    description: "Alquiler del local — mayo 2026",
    category: "Instalaciones",
    expense_date: "2026-05-01",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 1,
    notes: "",
    created_at: "2026-05-01T08:00:00Z",
    updated_at: "2026-05-01T08:00:00Z",
  },
  {
    id: "exp-2",
    tenant_id: "demo",
    supplier_id: null,
    amount: 1500,
    description: "Servicio de Internet — mayo 2026",
    category: "Servicios",
    expense_date: "2026-05-05",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 5,
    notes: "Fibra óptica",
    created_at: "2026-05-05T08:00:00Z",
    updated_at: "2026-05-05T08:00:00Z",
  },
  {
    id: "exp-3",
    tenant_id: "demo",
    supplier_id: "sup-1",
    amount: 3200,
    description: "Reposición de bebidas y snacks",
    category: "Inventario",
    expense_date: "2026-05-08",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "Pedido semanal",
    created_at: "2026-05-08T10:30:00Z",
    updated_at: "2026-05-08T10:30:00Z",
  },
  {
    id: "exp-4",
    tenant_id: "demo",
    supplier_id: null,
    amount: 2500,
    description: "Factura eléctrica — mayo 2026",
    category: "Servicios",
    expense_date: "2026-05-15",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "",
    created_at: "2026-05-15T09:00:00Z",
    updated_at: "2026-05-15T09:00:00Z",
  },
  {
    id: "exp-5",
    tenant_id: "demo",
    supplier_id: "sup-3",
    amount: 750,
    description: "Material de limpieza",
    category: "Suministros",
    expense_date: "2026-05-20",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "Detergente, escobas, trapeadores",
    created_at: "2026-05-20T11:00:00Z",
    updated_at: "2026-05-20T11:00:00Z",
  },
  // ── Abril 2026 (historique) ───────────────────────────────────────────────
  {
    id: "exp-6",
    tenant_id: "demo",
    supplier_id: null,
    amount: 5000,
    description: "Alquiler del local — abril 2026",
    category: "Instalaciones",
    expense_date: "2026-04-01",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 1,
    notes: "",
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "exp-7",
    tenant_id: "demo",
    supplier_id: null,
    amount: 1500,
    description: "Servicio de Internet — abril 2026",
    category: "Servicios",
    expense_date: "2026-04-05",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 5,
    notes: "",
    created_at: "2026-04-05T08:00:00Z",
    updated_at: "2026-04-05T08:00:00Z",
  },
  {
    id: "exp-8",
    tenant_id: "demo",
    supplier_id: "sup-2",
    amount: 4500,
    description: "Compra de cables USB-C (lote)",
    category: "Inventario",
    expense_date: "2026-04-12",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "50 unidades cable 1m + 20 unidades cable 2m",
    created_at: "2026-04-12T14:00:00Z",
    updated_at: "2026-04-12T14:00:00Z",
  },
];

// ─── Cash Closings ────────────────────────────────────────────────────────────
// Pre-seeded closings for d(1), d(2), d(3) — amounts match DEMO_TRANSACTIONS
const dStr = (offsetDays: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - offsetDays);
  return date.toISOString().split("T")[0];
};

export const DEMO_CASH_CLOSINGS_INITIAL = [
  // 3 days ago: TXN-005 CASH 310.50
  {
    id: "closing-1",
    tenant_id: "demo",
    closing_date: dStr(3),
    system_cash: 310.50,
    system_card: 0,
    system_transfer: 0,
    system_total: 310.50,
    declared_cash: 310.50,
    declared_card: 0,
    declared_transfer: 0,
    diff_cash: 0,
    diff_card: 0,
    diff_transfer: 0,
    notes: "Cierre sin diferencias",
    closed_by: "Juan García",
    closing_time: d(3, 18, 0),
    created_at: d(3, 18, 0),
  },
  // 2 days ago: TXN-004 CASH 138
  {
    id: "closing-2",
    tenant_id: "demo",
    closing_date: dStr(2),
    system_cash: 138,
    system_card: 0,
    system_transfer: 0,
    system_total: 138,
    declared_cash: 140,
    declared_card: 0,
    declared_transfer: 0,
    diff_cash: 2,
    diff_card: 0,
    diff_transfer: 0,
    notes: "Sobrante de C$2 (billete olvidado)",
    closed_by: "María López",
    closing_time: d(2, 19, 30),
    created_at: d(2, 19, 30),
  },
  // Yesterday: TXN-003 TRANSFER 207
  {
    id: "closing-3",
    tenant_id: "demo",
    closing_date: dStr(1),
    system_cash: 0,
    system_card: 0,
    system_transfer: 207,
    system_total: 207,
    declared_cash: 0,
    declared_card: 0,
    declared_transfer: 205,
    diff_cash: 0,
    diff_card: 0,
    diff_transfer: -2,
    notes: "Diferencia mínima en transferencia",
    closed_by: "Juan García",
    closing_time: d(1, 18, 45),
    created_at: d(1, 18, 45),
  },
];

