/**
 * Demo Mode — Mock Data
 * All demo data lives here. The demo API route (/api/tenants/demo/[...path]) serves this data.
 * Write operations (POST/PUT/DELETE) echo back the submitted payload — changes are NOT persisted.
 */

import { toNicaraguaDateString } from "@/lib/utils/formatters";

export const DEMO_TENANT_ID = "demo";

// ─── Tenant ──────────────────────────────────────────────────────────────────
export const DEMO_TENANT = {
  id: "demo",
  name: "Tienda Demo",
  slug: "demo",
  plan: "enterprise",
  features: {
    pos: true,
    inventory: true,
    employees: true,
    schedules: true,
    payroll: true,
    reports: true,
    customRoles: true,
    api: true,
    loyalty: true,
    expenses: true,
    taxes: true,
    contacts: true,
    settings: true,
  },
  paid_until: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
  created_at: "2024-01-01T00:00:00Z",
  updated_at: new Date().toISOString(),
};

// ─── Settings ─────────────────────────────────────────────────────────────────
export const DEMO_SETTINGS = {
  companyName: "ABC Web",
  companyPhone: "+505 2222-3333",
  companyEmail: "demo@abcweb.com",
  companyWebsite: "www.abcweb.com",
  companyRuc: "J0310000123456",
  currency: "USD",
  timezone: "America/Managua",
  language: "en",
  usdExchangeRate: 36.80,
  logoUrl: null,
  posConfig: { roundTotal: false, printReceipt: true },
  payrollConfig: { frequency: "weekly", weekStartDay: 1, monthStartDay: 1 },
};

// ─── Categories ───────────────────────────────────────────────────────────────
// `name`/`description` stay in Spanish as the default (non-localized) value for
// backward compatibility; `name_i18n`/`description_i18n` provide the 3 demo
// locales (es-ni, en, fr) and are resolved server-side based on the active
// language — see `localizeCategories()` in the demo API route.
export const DEMO_CATEGORIES = [
  { id: "cat-1", tenant_id: "demo", name: "Bebidas", name_i18n: { "es-ni": "Bebidas", en: "Beverages", fr: "Boissons" }, description: "Refrescos, jugos, agua", description_i18n: { "es-ni": "Refrescos, jugos, agua", en: "Sodas, juices, water", fr: "Boissons gazeuses, jus, eau" }, sort_order: 1, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-2", tenant_id: "demo", name: "Alimentos", name_i18n: { "es-ni": "Alimentos", en: "Food", fr: "Alimentation" }, description: "Snacks, galletas, comida rápida", description_i18n: { "es-ni": "Snacks, galletas, comida rápida", en: "Snacks, cookies, fast food", fr: "Collations, biscuits, restauration rapide" }, sort_order: 2, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-3", tenant_id: "demo", name: "Electrónica", name_i18n: { "es-ni": "Electrónica", en: "Electronics", fr: "Électronique" }, description: "Accesorios y gadgets", description_i18n: { "es-ni": "Accesorios y gadgets", en: "Accessories and gadgets", fr: "Accessoires et gadgets" }, sort_order: 3, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "cat-4", tenant_id: "demo", name: "Higiene Personal", name_i18n: { "es-ni": "Higiene Personal", en: "Personal Care", fr: "Hygiène Personnelle" }, description: "Jabones, shampoo, desodorante", description_i18n: { "es-ni": "Jabones, shampoo, desodorante", en: "Soaps, shampoo, deodorant", fr: "Savons, shampooing, déodorant" }, sort_order: 4, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];

// ─── Products ─────────────────────────────────────────────────────────────────
// `name`/`description` stay in Spanish as the default (non-localized) value;
// `name_i18n`/`description_i18n` provide the 3 demo locales (es-ni, en, fr)
// and are resolved server-side — see `localizeProducts()` in the demo API route.
export const DEMO_PRODUCTS = [
  {
    id: "prod-1",
    tenant_id: "demo",
    name: "Coca-Cola",
    name_i18n: { "es-ni": "Coca-Cola", en: "Coca-Cola", fr: "Coca-Cola" },
    sku: "BEB-001",
    price: 3,
    quantity: 48,
    stock_quantity: 48,
    category_id: "cat-1",
    description: "Refresco 355ml",
    description_i18n: { "es-ni": "Refresco 355ml", en: "355ml soda", fr: "Boisson gazeuse 355ml" },
    min_stock: 10,
    sort_order: 1,
    has_variants: false,
    variants: [],
    cost_price: 2.27,
    image: "/images/products/coca-cola.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-2",
    tenant_id: "demo",
    name: "Pepsi",
    name_i18n: { "es-ni": "Pepsi", en: "Pepsi", fr: "Pepsi" },
    sku: "BEB-002",
    price: 2.27,
    quantity: 36,
    stock_quantity: 36,
    category_id: "cat-1",
    description: "Refresco 355ml",
    description_i18n: { "es-ni": "Refresco 355ml", en: "355ml soda", fr: "Boisson gazeuse 355ml" },
    min_stock: 10,
    sort_order: 2,
    has_variants: false,
    variants: [],
    cost_price: 2.27,
    image: "/images/products/pepsi.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-3",
    tenant_id: "demo",
    name: "Agua Purificada",
    name_i18n: { "es-ni": "Agua Purificada", en: "Purified Water", fr: "Eau Purifiée" },
    sku: "BEB-003",
    price: 1.29,
    quantity: 120,
    stock_quantity: 120,
    category_id: "cat-1",
    description: "Botella 500ml",
    description_i18n: { "es-ni": "Botella 500ml", en: "500ml bottle", fr: "Bouteille 500ml" },
    min_stock: 20,
    sort_order: 3,
    has_variants: false,
    variants: [],
    cost_price: 1.5,
    image: "/images/products/water.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-4",
    tenant_id: "demo",
    name: "Café Presto",
    name_i18n: { "es-ni": "Café Presto", en: "Presto Instant Coffee", fr: "Café Instantané Presto" },
    sku: "BEB-004",
    price: 8.99,
    quantity: 3,
    stock_quantity: 3,
    category_id: "cat-1",
    description: "Café instantáneo 150g (stock bajo)",
    description_i18n: { "es-ni": "Café instantáneo 150g (stock bajo)", en: "Instant coffee 150g (low stock)", fr: "Café instantané 150g (stock bas)" },
    min_stock: 5,
    sort_order: 4,
    has_variants: false,
    variants: [],
    cost_price: 8.99,
    image: "/images/products/cafe-presto.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-5",
    tenant_id: "demo",
    name: "Chips Sabritas",
    name_i18n: { "es-ni": "Chips Sabritas", en: "Sabritas Chips", fr: "Croustilles Sabritas" },
    sku: "ALI-001",
    price: 25,
    quantity: 60,
    stock_quantity: 60,
    category_id: "cat-2",
    description: "Papas fritas 150g",
    description_i18n: { "es-ni": "Papas fritas 150g", en: "Potato chips 150g", fr: "Croustilles 150g" },
    min_stock: 10,
    sort_order: 5,
    has_variants: false,
    variants: [],
    cost_price: 1,
    image: "/images/products/sabritas-chips.jpg",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-6",
    tenant_id: "demo",
    name: "Galletas Oreo",
    name_i18n: { "es-ni": "Galletas Oreo", en: "Oreo Cookies", fr: "Biscuits Oreo" },
    sku: "ALI-002",
    price: 45,
    quantity: 40,
    stock_quantity: 40,
    category_id: "cat-2",
    description: "Galletas de chocolate 154g",
    description_i18n: { "es-ni": "Galletas de chocolate 154g", en: "Chocolate cookies 154g", fr: "Biscuits au chocolat 154g" },
    min_stock: 8,
    sort_order: 6,
    has_variants: false,
    variants: [],
    cost_price: 6.99,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-7",
    tenant_id: "demo",
    name: "Cable USB-C",
    name_i18n: { "es-ni": "Cable USB-C", en: "USB-C Cable", fr: "Câble USB-C" },
    sku: "ELE-001",
    price: 180,
    quantity: 15,
    stock_quantity: 15,
    category_id: "cat-3",
    description: "Cable de carga USB-C 1m",
    description_i18n: { "es-ni": "Cable de carga USB-C 1m", en: "USB-C charging cable 1m", fr: "Câble de charge USB-C 1m" },
    min_stock: 3,
    sort_order: 7,
    has_variants: true,
    cost_price: 13.49,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
    variants: [
      { id: "var-7-1", product_id: "prod-7", tenant_id: "demo", label: "1 metro", label_i18n: { "es-ni": "1 metro", en: "1 meter", fr: "1 mètre" }, sku: "ELE-001-1M", price: 180, stock_quantity: 10, sort_order: 1, cost_price: 90 },
      { id: "var-7-2", product_id: "prod-7", tenant_id: "demo", label: "2 metros", label_i18n: { "es-ni": "2 metros", en: "2 meters", fr: "2 mètres" }, sku: "ELE-001-2M", price: 250, stock_quantity: 5, sort_order: 2, cost_price: 130 },
    ],
  },
  {
    id: "prod-8",
    tenant_id: "demo",
    name: "Jabón Dove",
    name_i18n: { "es-ni": "Jabón Dove", en: "Dove Soap", fr: "Savon Dove" },
    sku: "HIG-001",
    price: 55,
    quantity: 25,
    stock_quantity: 25,
    category_id: "cat-4",
    description: "Jabón en barra 135g",
    description_i18n: { "es-ni": "Jabón en barra 135g", en: "Bar soap 135g", fr: "Savon en barre 135g" },
    min_stock: 5,
    sort_order: 8,
    has_variants: false,
    variants: [],
    cost_price: 6.99,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "prod-9",
    tenant_id: "demo",
    name: "Shampoo Head & Shoulders",
    name_i18n: { "es-ni": "Shampoo Head & Shoulders", en: "Head & Shoulders Shampoo", fr: "Shampooing Head & Shoulders" },
    sku: "HIG-002",
    price: 220,
    quantity: 0,
    stock_quantity: 0,
    category_id: "cat-4",
    description: "Shampoo anticaspa 400ml (agotado)",
    description_i18n: { "es-ni": "Shampoo anticaspa 400ml (agotado)", en: "Anti-dandruff shampoo 400ml (out of stock)", fr: "Shampooing antipelliculaire 400ml (rupture de stock)" },
    min_stock: 3,
    sort_order: 9,
    has_variants: false,
    variants: [],
    cost_price: 8.99,
    image: null,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Taxes ────────────────────────────────────────────────────────────────────
// `name` stays as the default (non-localized) value; `name_i18n` provides the
// 3 demo locales (es-ni, en, fr) — see `localizeTaxes()` in the demo API route.
export const DEMO_TAXES = [
  {
    id: "tax-1",
    tenant_id: "demo",
    name: "TAXE",
    name_i18n: { "es-ni": "TAXE", en: "Tax", fr: "Taxe" },
    rate: 15,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
// Nicaragua is UTC-6 year-round (no DST). Demo "today" is anchored to Nicaragua's calendar
// day — not the server process's local/UTC day — so seeded dates always agree with
// `toNicaraguaDateString()`, used across the app to bucket records by day. Otherwise, during
// the 00:00–06:00 UTC window (18:00–00:00 Nicaragua time), seeded "today" records would be
// dated one day ahead of what the rest of the app considers "today".
const now = new Date();
const todayNi = toNicaraguaDateString(now);
/** Adds (or subtracts) days from a "YYYY-MM-DD" string, returning a new "YYYY-MM-DD" string. */
const addDaysStr = (dateStr: string, days: number): string => {
  const [y, m, dd] = dateStr.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, dd + days)).toISOString().slice(0, 10);
};
const d = (offsetDays: number, h = 10, m = 0) => {
  const dateStr = addDaysStr(todayNi, -offsetDays);
  const hh = String(h).padStart(2, "0");
  const mm = String(m).padStart(2, "0");
  return new Date(`${dateStr}T${hh}:${mm}:00-06:00`).toISOString();
};

export const DEMO_TRANSACTIONS = [
  {
    id: "TXN-DEMO-001",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-1", name: "Coca-Cola", quantity: 2, price: 35, cost_price: 20, total: 70 },
      { productId: "prod-5", name: "Chips Sabritas", quantity: 1, price: 25, cost_price: 14, total: 25 },
    ],
    subtotal: 95,
    discount: 0,
    tax: 14.25,
    total: 109.25,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(0, 9, 15),
    updated_at: d(0, 9, 15),
  },
  {
    id: "TXN-DEMO-002",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "María Demo",
    items: [
      { productId: "prod-7", variantId: "var-7-1", name: "Cable USB-C — 1 metro", quantity: 1, price: 180, cost_price: 90, total: 180 },
      { productId: "prod-8", name: "Jabón Dove", quantity: 3, price: 55, cost_price: 30, total: 165 },
    ],
    subtotal: 345,
    discount: 20,
    tax: 48.75,
    total: 373.75,
    payment_method: "CARD",
    status: "COMPLETED",
    created_at: d(0, 11, 30),
    updated_at: d(0, 11, 30),
  },
  {
    id: "TXN-DEMO-003",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-3", name: "Agua Purificada", quantity: 6, price: 15, cost_price: 7, total: 90 },
      { productId: "prod-6", name: "Galletas Oreo", quantity: 2, price: 45, cost_price: 25, total: 90 },
    ],
    subtotal: 180,
    discount: 0,
    tax: 27,
    total: 207,
    payment_method: "TRANSFER",
    status: "COMPLETED",
    created_at: d(1, 14, 45),
    updated_at: d(1, 14, 45),
  },
  {
    id: "TXN-DEMO-004",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "María Demo",
    items: [
      { productId: "prod-2", name: "Pepsi", quantity: 4, price: 30, cost_price: 17, total: 120 },
    ],
    subtotal: 120,
    discount: 0,
    tax: 18,
    total: 138,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(2, 10, 0),
    updated_at: d(2, 10, 0),
  },
  {
    id: "TXN-DEMO-005",
    tenant_id: "demo",
    cashier_id: "demo-user",
    cashier_name: "Juan Demo",
    items: [
      { productId: "prod-4", name: "Café Presto", quantity: 1, price: 50, cost_price: 28, total: 50 },
      { productId: "prod-7", variantId: "var-7-2", name: "Cable USB-C — 2 metros", quantity: 1, price: 250, cost_price: 130, total: 250 },
    ],
    subtotal: 300,
    discount: 30,
    tax: 40.5,
    total: 310.5,
    payment_method: "CASH",
    status: "COMPLETED",
    created_at: d(3, 16, 20),
    updated_at: d(3, 16, 20),
  },
];

// ─── Employees ────────────────────────────────────────────────────────────────
export const DEMO_EMPLOYEES = [
  {
    id: "emp-1",
    tenant_id: "demo",
    first_name: "Juan",
    last_name: "García",
    email: "juan.garcia@demo.com",
    phone: "+505 8888-1111",
    role_id: "cashier",
    salary: 7680,
    status: "ACTIVE",
    hire_date: "2023-03-15",
    created_at: "2023-03-15T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-2",
    tenant_id: "demo",
    first_name: "María",
    last_name: "López",
    email: "maria.lopez@demo.com",
    phone: "+505 8888-2222",
    role_id: "cashier",
    salary: 7200,
    status: "ACTIVE",
    hire_date: "2023-06-01",
    created_at: "2023-06-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-3",
    tenant_id: "demo",
    first_name: "Carlos",
    last_name: "Martínez",
    email: "carlos.martinez@demo.com",
    phone: "+505 8888-3333",
    role_id: "manager",
    salary: 15200,
    status: "ACTIVE",
    hire_date: "2022-11-01",
    created_at: "2022-11-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "emp-4",
    tenant_id: "demo",
    first_name: "Ana",
    last_name: "Rodríguez",
    email: "ana.rodriguez@demo.com",
    phone: "+505 8888-4444",
    role_id: "employee",
    salary: 6720,
    status: "INACTIVE",
    hire_date: "2023-01-10",
    created_at: "2023-01-10T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Attendance (Time Entries) ─────────────────────────────────────────────────
export const DEMO_ATTENDANCE = [
  {
    id: "att-1",
    tenant_id: "demo",
    employee_id: "emp-1",
    employee_first_name: "Juan",
    employee_last_name: "García",
    check_in: d(0, 8, 0),
    check_out: d(0, 17, 0),
    date: todayNi,
    notes: "",
    created_at: d(0, 8, 0),
  },
  {
    id: "att-2",
    tenant_id: "demo",
    employee_id: "emp-2",
    employee_first_name: "María",
    employee_last_name: "López",
    check_in: d(0, 8, 30),
    check_out: d(0, 17, 30),
    date: todayNi,
    notes: "",
    created_at: d(0, 8, 30),
  },
  {
    id: "att-3",
    tenant_id: "demo",
    employee_id: "emp-1",
    employee_first_name: "Juan",
    employee_last_name: "García",
    check_in: d(1, 8, 0),
    check_out: d(1, 17, 0),
    date: addDaysStr(todayNi, -1),
    notes: "Turno normal",
    created_at: d(1, 8, 0),
  },
  {
    id: "att-4",
    tenant_id: "demo",
    employee_id: "emp-3",
    employee_first_name: "Carlos",
    employee_last_name: "Martínez",
    check_in: d(1, 7, 0),
    check_out: d(1, 16, 0),
    date: addDaysStr(todayNi, -1),
    notes: "Turno mañana",
    created_at: d(1, 7, 0),
  },
];

// ─── Payroll ──────────────────────────────────────────────────────────────────
export const DEMO_PAYROLL_CONFIG = {
  frequency: "weekly",
  weekStartDay: 1,
  monthStartDay: 1,
};

export const DEMO_SALARY_PAYMENTS = [
  // ── Semaine 14 avril (lun 14 → dim 20 avr 2026) ──────────────────────────
  {
    id: "pay-1",
    tenant_id: "demo",
    employee_id: "emp-1",
    employees: { first_name: "Juan", last_name: "García" },
    period_start: "2026-04-14",
    period_end: "2026-04-20",
    hours_worked: 44,
    hourly_rate: 48,
    amount: 2112,
    notes: "Semana con horas extras",
    paid_at: "2026-04-20",
    created_at: "2026-04-20T00:00:00Z",
  },
  {
    id: "pay-2",
    tenant_id: "demo",
    employee_id: "emp-2",
    employees: { first_name: "María", last_name: "López" },
    period_start: "2026-04-14",
    period_end: "2026-04-20",
    hours_worked: 40,
    hourly_rate: 45,
    amount: 1800,
    notes: "",
    paid_at: "2026-04-20",
    created_at: "2026-04-20T00:00:00Z",
  },
  {
    id: "pay-3",
    tenant_id: "demo",
    employee_id: "emp-3",
    employees: { first_name: "Carlos", last_name: "Martínez" },
    period_start: "2026-04-14",
    period_end: "2026-04-20",
    hours_worked: 40,
    hourly_rate: 95,
    amount: 3800,
    notes: "",
    paid_at: "2026-04-20",
    created_at: "2026-04-20T00:00:00Z",
  },
  // ── Semaine 21 avril (lun 21 → dim 27 avr 2026) ──────────────────────────
  {
    id: "pay-4",
    tenant_id: "demo",
    employee_id: "emp-1",
    employees: { first_name: "Juan", last_name: "García" },
    period_start: "2026-04-21",
    period_end: "2026-04-27",
    hours_worked: 40,
    hourly_rate: 48,
    amount: 1920,
    notes: "",
    paid_at: "2026-04-27",
    created_at: "2026-04-27T00:00:00Z",
  },
  {
    id: "pay-5",
    tenant_id: "demo",
    employee_id: "emp-2",
    employees: { first_name: "María", last_name: "López" },
    period_start: "2026-04-21",
    period_end: "2026-04-27",
    hours_worked: 40,
    hourly_rate: 45,
    amount: 1800,
    notes: "",
    paid_at: "2026-04-27",
    created_at: "2026-04-27T00:00:00Z",
  },
  {
    id: "pay-6",
    tenant_id: "demo",
    employee_id: "emp-3",
    employees: { first_name: "Carlos", last_name: "Martínez" },
    period_start: "2026-04-21",
    period_end: "2026-04-27",
    hours_worked: 40,
    hourly_rate: 95,
    amount: 3800,
    notes: "",
    paid_at: "2026-04-27",
    created_at: "2026-04-27T00:00:00Z",
  },
  // ── Semaine en cours (lun 28 avr → dim 3 mai 2026) ───────────────────────
  {
    id: "pay-7",
    tenant_id: "demo",
    employee_id: "emp-1",
    employees: { first_name: "Juan", last_name: "García" },
    period_start: "2026-04-28",
    period_end: "2026-05-04",
    hours_worked: 42,
    hourly_rate: 48,
    amount: 2016,
    notes: "Semana en curso",
    paid_at: null,
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "pay-8",
    tenant_id: "demo",
    employee_id: "emp-2",
    employees: { first_name: "María", last_name: "López" },
    period_start: "2026-04-28",
    period_end: "2026-05-04",
    hours_worked: 40,
    hourly_rate: 45,
    amount: 1800,
    notes: "",
    paid_at: null,
    created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: "pay-9",
    tenant_id: "demo",
    employee_id: "emp-3",
    employees: { first_name: "Carlos", last_name: "Martínez" },
    period_start: "2026-04-28",
    period_end: "2026-05-04",
    hours_worked: 40,
    hourly_rate: 95,
    amount: 3800,
    notes: "",
    paid_at: null,
    created_at: "2026-05-01T00:00:00Z",
  },
];

// ─── Roles ────────────────────────────────────────────────────────────────────
// `name`/`description` stay in Spanish as the default (non-localized) value;
// `name_i18n`/`description_i18n` provide the 3 demo locales (es-ni, en, fr)
// and are resolved server-side — see `localizeRoles()` in the demo API route.
export const DEMO_ROLES = [
  {
    id: "admin",
    tenant_id: "demo",
    slug: "admin",
    name: "Admin",
    name_i18n: { "es-ni": "Admin", en: "Admin", fr: "Admin" },
    description: "Acceso completo al sistema",
    description_i18n: { "es-ni": "Acceso completo al sistema", en: "Full access to the system", fr: "Accès complet au système" },
    permissions: [
      "pos.view", "pos.create", "pos.void", "pos.configure",
      "inventory.view", "inventory.create", "inventory.edit", "inventory.delete", "inventory.adjust",
      "employees.view", "employees.create", "employees.edit", "employees.delete",
      "schedules.view", "schedules.edit", "schedules.checkin",
      "payroll.view", "payroll.create", "payroll.approve", "payroll.pay",
      "settings.view", "settings.edit", "settings.manage_roles",
      "reports.view", "reports.export",
    ],
    is_system: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "manager",
    tenant_id: "demo",
    slug: "manager",
    name: "Manager",
    name_i18n: { "es-ni": "Gerente", en: "Manager", fr: "Gestionnaire" },
    description: "Gestión de empleados, inventario y reportes",
    description_i18n: { "es-ni": "Gestión de empleados, inventario y reportes", en: "Management of employees, inventory, and reports", fr: "Gestion des employés, de l'inventaire et des rapports" },
    permissions: [
      "pos.view", "pos.create",
      "inventory.view", "inventory.create", "inventory.edit",
      "employees.view", "employees.create", "employees.edit",
      "schedules.view", "schedules.edit",
      "payroll.view", "payroll.create",
      "reports.view", "reports.export",
    ],
    is_system: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cashier",
    tenant_id: "demo",
    slug: "cashier",
    name: "Staff",
    name_i18n: { "es-ni": "Personal", en: "Staff", fr: "Personnel" },
    description: "Operaciones de caja",
    description_i18n: { "es-ni": "Operaciones de caja", en: "Cash register operations", fr: "Opérations de caisse" },
    permissions: ["pos.view", "pos.create", "schedules.checkin"],
    is_system: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Loyalty ──────────────────────────────────────────────────────────────────
export const DEMO_LOYALTY_SETTINGS = {
  loyalty_module_enabled: true,
  points_per_purchase: 1,
  min_purchase_for_points: 100,
};

export const DEMO_LOYAL_CUSTOMERS = [
  {
    id: "lc-1",
    tenant_id: "demo",
    card_number: "12345",
    name: "Roberto Sánchez",
    phone: "+505 7777-1111",
    email: "roberto@demo.com",
    total_accumulated: 3500,
    total_visits: 28,
    created_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "lc-2",
    tenant_id: "demo",
    card_number: "67890",
    name: "Lucía Peña",
    phone: "+505 7777-2222",
    email: "lucia@demo.com",
    total_accumulated: 1200,
    total_visits: 10,
    created_at: "2024-02-01T00:00:00Z",
  },
];

// ─── Payment status ───────────────────────────────────────────────────────────
export const DEMO_PAYMENT_STATUS = {
  is_paid: true,
  paid_until: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
  plan: "enterprise",
  amount: 0,
};

// ─── Contacts ─────────────────────────────────────────────────────────────────
// `position`/`notes` stay in Spanish as the default (non-localized) value;
// `position_i18n`/`notes_i18n` provide the 3 demo locales (es-ni, en, fr) —
// see `localizeContacts()` in the demo API route.
export const DEMO_CONTACTS_INITIAL = [
  {
    id: "demo-contact-1",
    tenant_id: "demo",
    full_name: "María García",
    email: "maria.garcia@ejemplo.com",
    phone_number: "+505 8765-4321",
    whatsapp_number: "+505 8765-4321",
    company_name: "Distribuidora García",
    address: "Barrio Los Robles, Casa 12",
    city: "Managua",
    country: "Nicaragua",
    postal_code: "",
    position: "Gerente General",
    position_i18n: { "es-ni": "Gerente General", en: "General Manager", fr: "Directrice Générale" },
    notes: "Cliente frecuente, prefiere pago en efectivo.",
    notes_i18n: { "es-ni": "Cliente frecuente, prefiere pago en efectivo.", en: "Frequent customer, prefers cash payment.", fr: "Cliente fréquente, préfère le paiement en espèces." },
    google_maps_link: "",
    photo_url: null,
    created_at: "2024-03-15T10:00:00Z",
    updated_at: "2024-03-15T10:00:00Z",
  },
  {
    id: "demo-contact-2",
    tenant_id: "demo",
    full_name: "Carlos Rodríguez",
    email: "c.rodriguez@suplidores.ni",
    phone_number: "+505 2222-3344",
    whatsapp_number: "",
    company_name: "Suplidores del Norte",
    address: "Km 5 Carretera Norte",
    city: "Managua",
    country: "Nicaragua",
    postal_code: "",
    position: "Representante de Ventas",
    position_i18n: { "es-ni": "Representante de Ventas", en: "Sales Representative", fr: "Représentant Commercial" },
    notes: "Proveedor principal de electrónicos.",
    notes_i18n: { "es-ni": "Proveedor principal de electrónicos.", en: "Main electronics supplier.", fr: "Principal fournisseur d'électronique." },
    google_maps_link: "",
    photo_url: null,
    created_at: "2024-04-01T09:30:00Z",
    updated_at: "2024-04-01T09:30:00Z",
  },
];

// ─── Suppliers ────────────────────────────────────────────────────────────────
// `name` (a company name) is not localized; `description` stays in Spanish as
// the default (non-localized) value, `description_i18n` provides the 3 demo
// locales (es-ni, en, fr) — see `localizeSuppliers()` in the demo API route.
export const DEMO_SUPPLIERS_INITIAL = [
  {
    id: "sup-1",
    tenant_id: "demo",
    name: "Distribuidora Nacional",
    description: "Proveedor de bebidas y alimentos",
    description_i18n: { "es-ni": "Proveedor de bebidas y alimentos", en: "Beverage and food supplier", fr: "Fournisseur de boissons et d'aliments" },
    contact: "+505 2200-1000",
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "sup-2",
    tenant_id: "demo",
    name: "TecnoElect SA",
    description: "Accesorios electrónicos y cables",
    description_i18n: { "es-ni": "Accesorios electrónicos y cables", en: "Electronic accessories and cables", fr: "Accessoires électroniques et câbles" },
    contact: "+505 2200-2000",
    created_at: "2024-01-10T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "sup-3",
    tenant_id: "demo",
    name: "Higiene y Más",
    description: "Productos de higiene y limpieza",
    description_i18n: { "es-ni": "Productos de higiene y limpieza", en: "Hygiene and cleaning products", fr: "Produits d'hygiène et de nettoyage" },
    contact: "+505 2200-3000",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
];

// ─── Expense categories ───────────────────────────────────────────────────────
// `name`/`description` stay in Spanish as the default (non-localized) value;
// `name_i18n`/`description_i18n` provide the 3 demo locales (es-ni, en, fr) —
// see `localizeExpenseCategories()` in the demo API route.
export const DEMO_EXPENSE_CATEGORIES = [
  { id: "ecat-1", tenant_id: "demo", name: "Instalaciones", name_i18n: { "es-ni": "Instalaciones", en: "Facilities", fr: "Installations" }, description: "Alquiler y mantenimiento del local", description_i18n: { "es-ni": "Alquiler y mantenimiento del local", en: "Rent and premises maintenance", fr: "Loyer et entretien du local" }, created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-2", tenant_id: "demo", name: "Servicios",     name_i18n: { "es-ni": "Servicios", en: "Utilities", fr: "Services" },             description: "Electricidad, agua, internet",          description_i18n: { "es-ni": "Electricidad, agua, internet", en: "Electricity, water, internet", fr: "Électricité, eau, internet" },          created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-3", tenant_id: "demo", name: "Inventario",    name_i18n: { "es-ni": "Inventario", en: "Inventory", fr: "Inventaire" },           description: "Reposición de mercancía",               description_i18n: { "es-ni": "Reposición de mercancía", en: "Merchandise restocking", fr: "Réapprovisionnement de marchandises" },               created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-4", tenant_id: "demo", name: "Suministros",   name_i18n: { "es-ni": "Suministros", en: "Supplies", fr: "Fournitures" },          description: "Material de oficina y limpieza",        description_i18n: { "es-ni": "Material de oficina y limpieza", en: "Office and cleaning supplies", fr: "Fournitures de bureau et de nettoyage" },        created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
  { id: "ecat-5", tenant_id: "demo", name: "Transporte",    name_i18n: { "es-ni": "Transporte", en: "Transportation", fr: "Transport" },       description: "Fletes y gasolina",                     description_i18n: { "es-ni": "Fletes y gasolina", en: "Freight and gasoline", fr: "Fret et essence" },                     created_at: "2024-01-01T00:00:00Z", updated_at: "2024-01-01T00:00:00Z" },
];

// ─── Fixed expenses ───────────────────────────────────────────────────────────
// `name`/`notes` stay in Spanish as the default (non-localized) value;
// `name_i18n`/`notes_i18n` provide the 3 demo locales (es-ni, en, fr). The
// `category` field is re-mapped at serve-time from `DEMO_EXPENSE_CATEGORIES`
// — see `localizeFixedExpenses()` in the demo API route.
export const DEMO_FIXED_EXPENSES = [
  {
    id: "fix-1",
    tenant_id: "demo",
    name: "Alquiler del local",
    name_i18n: { "es-ni": "Alquiler del local", en: "Premises rent", fr: "Loyer du local" },
    amount: 5000,
    category: "Instalaciones",
    supplier_id: null,
    day_of_month: 1,
    notes: "Pago mensual por adelantado",
    notes_i18n: { "es-ni": "Pago mensual por adelantado", en: "Monthly payment in advance", fr: "Paiement mensuel d'avance" },
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "fix-2",
    tenant_id: "demo",
    name: "Servicio de Internet",
    name_i18n: { "es-ni": "Servicio de Internet", en: "Internet service", fr: "Service Internet" },
    amount: 1500,
    category: "Servicios",
    supplier_id: null,
    day_of_month: 5,
    notes: "Fibra óptica 100 Mbps",
    notes_i18n: { "es-ni": "Fibra óptica 100 Mbps", en: "100 Mbps fiber optic", fr: "Fibre optique 100 Mbps" },
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ─── Expenses ─────────────────────────────────────────────────────────────────
// Dates in current month (May 2026) so they appear in the Bilan's default filter
// `description`/`notes` stay in Spanish as the default (non-localized) value;
// `description_i18n`/`notes_i18n` provide the 3 demo locales (es-ni, en, fr).
// The `category` field is re-mapped at serve-time from `DEMO_EXPENSE_CATEGORIES`
// — see `localizeExpenses()` in the demo API route.
export const DEMO_EXPENSES_INITIAL = [
  {
    id: "exp-1",
    tenant_id: "demo",
    supplier_id: null,
    amount: 5000,
    description: "Alquiler del local — mayo 2026",
    description_i18n: { "es-ni": "Alquiler del local — mayo 2026", en: "Premises rent — May 2026", fr: "Loyer du local — mai 2026" },
    category: "Instalaciones",
    expense_date: "2026-05-01",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 1,
    notes: "",
    notes_i18n: { "es-ni": "", en: "", fr: "" },
    created_at: "2026-05-01T08:00:00Z",
    updated_at: "2026-05-01T08:00:00Z",
  },
  {
    id: "exp-2",
    tenant_id: "demo",
    supplier_id: null,
    amount: 1500,
    description: "Servicio de Internet — mayo 2026",
    description_i18n: { "es-ni": "Servicio de Internet — mayo 2026", en: "Internet service — May 2026", fr: "Service Internet — mai 2026" },
    category: "Servicios",
    expense_date: "2026-05-05",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 5,
    notes: "Fibra óptica",
    notes_i18n: { "es-ni": "Fibra óptica", en: "Fiber optic", fr: "Fibre optique" },
    created_at: "2026-05-05T08:00:00Z",
    updated_at: "2026-05-05T08:00:00Z",
  },
  {
    id: "exp-3",
    tenant_id: "demo",
    supplier_id: "sup-1",
    amount: 3200,
    description: "Reposición de bebidas y snacks",
    description_i18n: { "es-ni": "Reposición de bebidas y snacks", en: "Beverage and snack restocking", fr: "Réapprovisionnement de boissons et collations" },
    category: "Inventario",
    expense_date: "2026-05-08",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "Pedido semanal",
    notes_i18n: { "es-ni": "Pedido semanal", en: "Weekly order", fr: "Commande hebdomadaire" },
    created_at: "2026-05-08T10:30:00Z",
    updated_at: "2026-05-08T10:30:00Z",
  },
  {
    id: "exp-4",
    tenant_id: "demo",
    supplier_id: null,
    amount: 2500,
    description: "Factura eléctrica — mayo 2026",
    description_i18n: { "es-ni": "Factura eléctrica — mayo 2026", en: "Electricity bill — May 2026", fr: "Facture d'électricité — mai 2026" },
    category: "Servicios",
    expense_date: "2026-05-15",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "",
    notes_i18n: { "es-ni": "", en: "", fr: "" },
    created_at: "2026-05-15T09:00:00Z",
    updated_at: "2026-05-15T09:00:00Z",
  },
  {
    id: "exp-5",
    tenant_id: "demo",
    supplier_id: "sup-3",
    amount: 750,
    description: "Material de limpieza",
    description_i18n: { "es-ni": "Material de limpieza", en: "Cleaning supplies", fr: "Matériel de nettoyage" },
    category: "Suministros",
    expense_date: "2026-05-20",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "Detergente, escobas, trapeadores",
    notes_i18n: { "es-ni": "Detergente, escobas, trapeadores", en: "Detergent, brooms, mops", fr: "Détergent, balais, serpillières" },
    created_at: "2026-05-20T11:00:00Z",
    updated_at: "2026-05-20T11:00:00Z",
  },
  // ── Abril 2026 (historique) ───────────────────────────────────────────────
  {
    id: "exp-6",
    tenant_id: "demo",
    supplier_id: null,
    amount: 5000,
    description: "Alquiler del local — abril 2026",
    description_i18n: { "es-ni": "Alquiler del local — abril 2026", en: "Premises rent — April 2026", fr: "Loyer du local — avril 2026" },
    category: "Instalaciones",
    expense_date: "2026-04-01",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 1,
    notes: "",
    notes_i18n: { "es-ni": "", en: "", fr: "" },
    created_at: "2026-04-01T08:00:00Z",
    updated_at: "2026-04-01T08:00:00Z",
  },
  {
    id: "exp-7",
    tenant_id: "demo",
    supplier_id: null,
    amount: 1500,
    description: "Servicio de Internet — abril 2026",
    description_i18n: { "es-ni": "Servicio de Internet — abril 2026", en: "Internet service — April 2026", fr: "Service Internet — avril 2026" },
    category: "Servicios",
    expense_date: "2026-04-05",
    is_recurring: true,
    recurring_frequency: "monthly",
    recurring_day_of_month: 5,
    notes: "",
    notes_i18n: { "es-ni": "", en: "", fr: "" },
    created_at: "2026-04-05T08:00:00Z",
    updated_at: "2026-04-05T08:00:00Z",
  },
  {
    id: "exp-8",
    tenant_id: "demo",
    supplier_id: "sup-2",
    amount: 4500,
    description: "Compra de cables USB-C (lote)",
    description_i18n: { "es-ni": "Compra de cables USB-C (lote)", en: "USB-C cable purchase (batch)", fr: "Achat de câbles USB-C (lot)" },
    category: "Inventario",
    expense_date: "2026-04-12",
    is_recurring: false,
    recurring_frequency: "",
    recurring_day_of_month: null,
    notes: "50 unidades cable 1m + 20 unidades cable 2m",
    notes_i18n: { "es-ni": "50 unidades cable 1m + 20 unidades cable 2m", en: "50 units 1m cable + 20 units 2m cable", fr: "50 unités câble 1m + 20 unités câble 2m" },
    created_at: "2026-04-12T14:00:00Z",
    updated_at: "2026-04-12T14:00:00Z",
  },
];

// ─── Cash Closings ────────────────────────────────────────────────────────────
// Pre-seeded closings for d(1), d(2), d(3) — amounts match DEMO_TRANSACTIONS
// `notes` stays in Spanish as the default (non-localized) value; `notes_i18n`
// provides the 3 demo locales (es-ni, en, fr) — see `localizeCashClosings()`
// in the demo API route.
// `dStr` reuses the Nicaragua-anchored `todayNi`/`addDaysStr` helpers defined above
// (with `d()`) so closing dates always agree with the rest of the app's "today".
const dStr = (offsetDays: number) => addDaysStr(todayNi, -offsetDays);

export const DEMO_CASH_CLOSINGS_INITIAL = [
  // 3 days ago: TXN-005 CASH 310.50
  {
    id: "closing-1",
    tenant_id: "demo",
    closing_date: dStr(3),
    system_cash: 310.50,
    system_card: 0,
    system_transfer: 0,
    system_total: 310.50,
    declared_cash: 310.50,
    declared_card: 0,
    declared_transfer: 0,
    diff_cash: 0,
    diff_card: 0,
    diff_transfer: 0,
    notes: "Cierre sin diferencias",
    notes_i18n: { "es-ni": "Cierre sin diferencias", en: "Closing with no discrepancies", fr: "Clôture sans écarts" },
    closed_by: "Juan García",
    closing_time: d(3, 18, 0),
    created_at: d(3, 18, 0),
  },
  // 2 days ago: TXN-004 CASH 138
  {
    id: "closing-2",
    tenant_id: "demo",
    closing_date: dStr(2),
    system_cash: 138,
    system_card: 0,
    system_transfer: 0,
    system_total: 138,
    declared_cash: 140,
    declared_card: 0,
    declared_transfer: 0,
    diff_cash: 2,
    diff_card: 0,
    diff_transfer: 0,
    notes: "Sobrante de C$2 (billete olvidado)",
    notes_i18n: { "es-ni": "Sobrante de C$2 (billete olvidado)", en: "C$2 overage (forgotten bill)", fr: "Excédent de C$2 (billet oublié)" },
    closed_by: "María López",
    closing_time: d(2, 19, 30),
    created_at: d(2, 19, 30),
  },
  // Yesterday: TXN-003 TRANSFER 207
  {
    id: "closing-3",
    tenant_id: "demo",
    closing_date: dStr(1),
    system_cash: 0,
    system_card: 0,
    system_transfer: 207,
    system_total: 207,
    declared_cash: 0,
    declared_card: 0,
    declared_transfer: 205,
    diff_cash: 0,
    diff_card: 0,
    diff_transfer: -2,
    notes: "Diferencia mínima en transferencia",
    notes_i18n: { "es-ni": "Diferencia mínima en transferencia", en: "Minimal transfer discrepancy", fr: "Écart minime sur le virement" },
    closed_by: "Juan García",
    closing_time: d(1, 18, 45),
    created_at: d(1, 18, 45),
  },
];

